version: "3.8"
networks:
  internal_c:
    name: internal_c
    driver: macvlan
    driver_opts:
      parent: ens19
    ipam:
      config:
        - subnet: "internal_c_subnet"
          gateway: "internal_c_gateway"
  dmz_c:
    name: dmz_c
    driver: bridge
    ipam:
      config:
        - subnet: "dmz_c_subnet"
          gateway: "dmz_c_gateway"
  pubnet:
    name: pubnet
    ipam:
      config:
        - subnet: "pubnet_subnet"
          gateway: "pubnet_gateway"
  internet:
    name: internet
    driver: macvlan
    driver_opts:
      parent: ens20
    ipam:
      config:
        - subnet: "internet_subnet"
          gateway: "internet_gateway"

services:
  # DMZ
  er_c: # Connects to dmz and pubnet
    build: ./edge_router
    container_name: er_c
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    entrypoint: er_c_entrypoint
    networks:
      dmz_c:
        ipv4_address: er_c_dmz_c
      pubnet:
        ipv4_address: er_c_pubnet
      internet:
        ipv4_address: er_c_internet
  r_c: # Also connects to internal
    build: ./router
    container_name: r_c
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    entrypoint: r_c_entrypoint
    networks:
      internal_c:
        ipv4_address: r_c_internal_c
      dmz_c:
        ipv4_address: r_c_dmz_c
  firewall:
    build: ./firewall
    container_name: firewall
    cap_add:
      - NET_ADMIN
    entrypoint: firewall_entrypoint
    networks:
      dmz_c:
        ipv4_address: firewall_dmz_c
  nagios:
    build: ./nagios
    container_name: nagios
    cap_add:
      - NET_ADMIN
    entrypoint: nagios_entrypoint
    networks:
      internal_c:
        ipv4_address: nagios_internal_c
  # Internal
  netmanager1:
    build: ./netmanager
    container_name: netmanager1
    cap_add:
      - NET_ADMIN
    networks:
      internal_c:
        ipv4_address: netmanager1_internal_c
  dhcp_c:
    build: ./dhcp
    container_name: dhcp_c
    cap_add:
      - NET_ADMIN
    entrypoint: dhcp_c_entrypoint
    networks:
      internal_c:
        ipv4_address: dhcp_c_internal_c
